description: Lovely furry thing. Meow!!
storage: db
plural: Cats
group: Animals
fields:
  id:
    label: Cat ID
    type: id
  name:
    label: Name
    description: The name of the cat
    type: string
    index: true
    required: true
    title: true
  toys:
    label: Toys
    type: object
    description: A inventory of the Cat's toys
    fields:
      name:
        label: Name
        type: string
        description: The name of the toy
      size:
        label: Size
        type: string
        description: The toy size
        values:
          large:
            label: Large
          medium:
            label: Small
          small:
            label: Small
      quantity:
        label: Quantity
        type: float
      attributes:
        label: Toy attributes
        type: object
        description: Key/values that describe the toy
        fields:
          key:
            label: Key
            type: string
            description: The attribute key
          value:
            label: Value
            type: string
            description: The attribute value
          publishPublicly:
            type: string
            label: Publish Publicly
        many: true
    many: true
  breeds:
    type: string
    label: Breeds
    many: true
    description: The breeds of cat
    default: Lab
  livesWithDogs:
    label: Lives with dogs
    description: The dogs that the cat lives with
    type: reference
    references: Dog
    many: true
  location:
    type: object
    label: Location
    fields:
      line1:
        type: string
        label: Line1
      line2:
        type: string
        label: Line2
    description: Home of the cat
  juneObject:
    type: object
    label: June object
    fields:
      blah1:
        type: string
        label: Blah 1
        required: true
  cost:
    type: float
    label: Cost
    required: true
    default: '66'
revisions: true
